apiVersion: v1
kind: ServiceAccount
metadata:
  name: gondolin-user-sim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gondolin-user-sim-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gondolin-user-sim-metrics
subjects:
  - kind: ServiceAccount
    name: gondolin-user-sim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gondolin-user-sim-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gondolin-user-sim-node-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gondolin-user-sim-node-metrics
subjects:
  - kind: ServiceAccount
    name: gondolin-user-sim
    namespace: gondolin-sim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gondolin-user-sim-node-metrics
